import React from 'react';
import { 
  BarChart3, Wallet, BrainCircuit, List, CreditCard, Plus, Trash2, Calendar, 
  ChevronLeft, ChevronRight, FileText, Download, Lightbulb, TrendingUp, 
  TrendingDown, LogOut, Moon, Search, Target, Settings, Save, Upload, Eye, 
  EyeOff, RefreshCw, PieChart, Home, Gem, PenTool, Star, Bell, Flame, X, Gift,
  Wand2, Mic, Sparkles, Award, Calculator, ShoppingCart, Percent, CheckSquare,
  Tv, Music, Repeat, Globe, Snowflake, Hash, Tag, Lock, Plane, Sheet
} from 'lucide-react';

export const Icon = ({ name, size=20, className="" }) => {
    const icons = {
        chart: <BarChart3 size={size} />,
        wallet: <Wallet size={size} />,
        brain: <BrainCircuit size={size} />,
        list: <List size={size} />,
        credit: <CreditCard size={size} />,
        plus: <Plus size={size} />,
        trash: <Trash2 size={size} />,
        calendar: <Calendar size={size} />,
        left: <ChevronLeft size={size} />,
        right: <ChevronRight size={size} />,
        file: <FileText size={size} />,
        download: <Download size={size} />,
        bulb: <Lightbulb size={size} />,
        trendUp: <TrendingUp size={size} />,
        trendDown: <TrendingDown size={size} />,
        logOut: <LogOut size={size} />,
        moon: <Moon size={size} />,
        search: <Search size={size} />,
        target: <Target size={size} />,
        settings: <Settings size={size} />,
        save: <Save size={size} />,
        upload: <Upload size={size} />,
        eye: <Eye size={size} />,
        eyeOff: <EyeOff size={size} />,
        refresh: <RefreshCw size={size} />,
        pie: <PieChart size={size} />,
        home: <Home size={size} />,
        diamond: <Gem size={size} />,
        tool: <PenTool size={size} />,
        star: <Star size={size} />,
        card: <CreditCard size={size} />,
        bell: <Bell size={size} />,
        fire: <Flame size={size} />,
        x: <X size={size} />,
        gift: <Gift size={size} />,
        magic: <Wand2 size={size} />,
        mic: <Mic size={size} />,
        sparkles: <Sparkles size={size} />,
        award: <Award size={size} />,
        calculator: <Calculator size={size} />,
        cart: <ShoppingCart size={size} />,
        percent: <Percent size={size} />,
        check: <CheckSquare size={size} />,
        tv: <Tv size={size} />,
        music: <Music size={size} />,
        repeat: <Repeat size={size} />,
        globe: <Globe size={size} />,
        snow: <Snowflake size={size} />,
        hash: <Hash size={size} />,
        tag: <Tag size={size} />,
        lock: <Lock size={size} />,
        plane: <Plane size={size} />,
        sheet: <FileText size={size} /> // Sheet fallback
    };
    return <span className={className}>{icons[name] || icons.chart}</span>;
};